version: '3'

services:
  postgres:
    image: postgres:11.1
    environment:
    - POSTGRES_DB=dashboard
    - POSTGRES_USER=dashboard
    - POSTGRES_PASSWORD=dashboard
    ports:
    - "5432:5432"
    volumes:
    - ./local/docker/postgres:/var/lib/postgresql:Z

  dashboard_app:
    build:
      context: .
      dockerfile: ./docker/dashboard/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./apps/dashboard:/dashboard
    depends_on:
      - postgres
    environment:
      - DEBUG=true
      - POSTGRES_DB=dashboard
      - POSTGRES_USER=dashboard
      - POSTGRES_PASSWORD=dashboard
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    ports:
       - "8000:8000"

  gen_image_app:
    image: onsdigital/highcharts-export-node