version: '3'

services:
  postgres:
    image: postgres:11.1
    environment:
    - POSTGRES_DB=dashboard
    - POSTGRES_USER=dashboard
    - POSTGRES_PASSWORD=dashboard
    volumes:
    - ./local/docker/postgres:/var/lib/postgresql:Z

  dashboard_app:
    build:
      context: .
      dockerfile: ./docker/dashboard/Dockerfile
    command: sh ../run_test_server.sh
    volumes:
      - ./apps/dashboard:/dashboard
    depends_on:
      - postgres
      - gen_data_app
      - gen_image_app
    environment:
      - DEBUG=true
      - POSTGRES_DB=dashboard
      - POSTGRES_USER=dashboard
      - POSTGRES_PASSWORD=dashboard
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - GEN_DATA_URL=http://gen_data_app:8888/get_data/
      - GEN_IMAGE_URL=http://gen_image_app:8080/
      - RABBITMQ_HOST=rabbit_mq
      - RABBITMQ_USER=rabbitmq
      - RABBITMQ_PASS=rabbitmq
      - REDIS_HOST=redis
    ports:
       - "8000:8000"

  gen_data_app:
    build:
      context: .
      dockerfile: ./docker/gen_data/Dockerfile
    command: bash -c "python -m app"
    volumes:
      - ./apps/gen_data/:/gen_data
    depends_on:
      - postgres
    environment:
      - DEBUG=true
      - SERVER_PORT=8888
      - POSTGRES_DB=dashboard
      - POSTGRES_USER=dashboard
      - POSTGRES_PASSWORD=dashboard
      - POSTGRES_HOST=postgres
    ports:
       - "8888:8888"

  gen_image_app:
    image: onsdigital/highcharts-export-node

  celery_worker_graphic:
    build:
      context: .
      dockerfile: ./docker/dashboard/Dockerfile
    command: 'python -m celery -A base worker -l debug -Q graphic'
    depends_on:
      - dashboard_app
      - rabbit_mq
      - redis
    volumes:
      - ./apps/dashboard:/dashboard
    environment:
      - DEBUG=true
      - POSTGRES_DB=dashboard
      - POSTGRES_USER=dashboard
      - POSTGRES_PASSWORD=dashboard
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - GEN_DATA_URL=http://gen_data_app:8888/get_data/
      - GEN_IMAGE_URL=http://gen_image_app:8080/
      - RABBITMQ_HOST=rabbit_mq
      - RABBITMQ_USER=rabbitmq
      - RABBITMQ_PASS=rabbitmq
      - REDIS_HOST=redis

  redis:
    image: "redis:alpine"
    restart: always

  rabbit_mq:
    image: rabbitmq:3-management
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "0"