# Generated by Django 2.1.3 on 2018-11-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Graphic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formula', models.CharField(choices=[('t', 't + 2/t'), ('s', 'sin(t)')], max_length=1, verbose_name='Функция')),
                ('interval', models.PositiveSmallIntegerField(verbose_name='Интервал t, дней')),
                ('dt', models.PositiveSmallIntegerField(verbose_name='Шаг t, часы')),
                ('date', models.DateTimeField(blank=True, verbose_name='Дата обработки')),
                ('image', models.ImageField(blank=True, upload_to='graphics')),
                ('error', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'verbose_name': 'График',
                'verbose_name_plural': 'Графики',
            },
        ),
    ]
