# Generated by Django 2.1.3 on 2018-11-18 16:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphic',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата обработки'),
        ),
        migrations.AlterField(
            model_name='graphic',
            name='dt',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)], verbose_name='Шаг t, часы'),
        ),
        migrations.AlterField(
            model_name='graphic',
            name='formula',
            field=models.CharField(choices=[('t', 't + 2/t'), ('s', 'sin(t)')], default='t', max_length=1, verbose_name='Функция'),
        ),
        migrations.AlterField(
            model_name='graphic',
            name='interval',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(355)], verbose_name='Интервал t, дней'),
        ),
    ]
